name: financy_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #animation
  flutter_animate: ^4.2.0
  google_fonts: ^5.1.0
  lottie: ^2.4.0
  #size
  flutter_screenutil: ^5.8.4
  #test
  mockito: ^5.4.2
  mocktail: ^0.3.0
  bloc_test: ^9.1.3
  #state
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  flutter_modular: ^6.0.3
  modular_bloc_bind: ^1.0.1
  #external
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  dio: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animations/
